{% set name = "nomad-camels-driver-trinamic-tmcm-1110" %}
{% set version = "0.1.1" %}
{% set python_min = "3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/nomad_camels_driver_trinamic_tmcm_1110-{{ version }}.tar.gz
  sha256: 7f04a85c2c91a2c09ff063187064ca6ba3cecb5128c985577891370f77fc4b8f

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=61.0
    - pip
  run:
    - python >={{ python_min }}
    - pytrinamic
    - nomad-camels

test:
  requires:
    - python {{ python_min }}
  imports:
    - nomad_camels_driver_trinamic_tmcm_1110

about:
  home: https://github.com/FAU-LAP/CAMELS_drivers
  summary: Instrument driver for Trinamic TMCM 1110 for NOMAD-CAMELS
  license: LGPL-2.1-or-later
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - jan-janssen
